### ISSUE TITLE
Cell Line Depmap Script OOM-Kill in the github actions pipeline.

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#89]
Continuous integration is failing in the Depmap build step of Cell Line the CI pipeline. It is exiting with exit code 137 which appears to be a memory issue.

I previously had a similar issue with beataml and I ended up trading time complexity for space complexity to get it efficient enough run in Github. This is difficult to reproduce locally but changes can be pushed to github and trigger the main.yml. This can be configured to trigger from any branch.

Looks like there is [14 GB](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners) of memory in the Git hub runners. I will make some small changes to the main.yml to see if I can save some memory in there (such as clearing the docker build cache) but this will likely require some updates to the code.

[Github action failure link](https://github.com/PNNL-CompBio/coderdata/actions/runs/7703958758/job/20998376626#step:9:111)

Command which the CI fails on:
```
docker run -v $PWD:/tmp cell-line Rscript 02-cellLineDepMap.R /tmp/genes.csv /tmp/cell_line_samples.csv
```

**Comment by sgosline** [comment]
For future reference: full repro steps are:
```
docker build -f ../dockerfile.cell_line -t cell-line ../
docker run -v $PWD:/tmp cell-line Rscript 02-cellLineDepMap.R /tmp/genes.csv /tmp/cell_line_samples.csv
```

I'm currently investigating.If i can't repro, I'll try to see what happens that could cause that.

**Comment by sgosline** [comment]
Actually that is wrong, the paths to the dockerfiles all changed. currently working on updating the docs so that I can build.

**Comment by jjacobson95** [comment]
Bug fix #92 failing earlier than previous version.
[Previous Version](https://github.com/PNNL-CompBio/coderdata/actions/runs/7744576955/job/21121792786#step:10:105): 16min 2sec - failing on a join step? After mutations.
[New Version](https://github.com/PNNL-CompBio/coderdata/actions/runs/7749054217/job/21133981161#step:10:31): 1min 43sec - failing early, maybe on first datatype generation.

I think it would be worth it filling this with debug statements to narrow down which line this is failing on and then working on reducing storage space complexity. 

Also, an idea for reproducing this locally could be to limit the memory available to docker desktop (should be in settings) to match 14GB (amount available on a runner) minus [7GB](https://github.com/PNNL-CompBio/coderdata/actions/runs/7750006335/job/21137861150#step:9:16) (space taken up by image plus a bit extra) - so run with 7GB memory space available.

**Comment by sgosline** [comment]
what branch is this in?

**Comment by jjacobson95** [comment]
I merged the changes from the cell-line-bug-fix branch (after the most recent PR) into builder_branch_JJ and ran it there.

**Comment by sgosline** [comment]
Ok, i'm able to get it to fail when reducing the memory. I've been working on this all day and still can't get it down below 8GB of RAM - are there any ways to increase the amount of memory? the image is only 2.3GB on my machine.

**Comment by jjacobson95** [comment]
I think we have 2 possible options - 
1) Keep working on reducing RAM required by the script. Maybe even convert to python or find an R package that has low memory utilities?
2) We could try to configure a self-hosted runner. So essentially GitHub actions would run on one of our laptops (or another PNNL machine). This might be tricky as the machine has to be constantly connected to the github servers.

**Comment by jjacobson95** [comment]
Actually, we may also be able to run this outside of a docker container. Though not ideal and not as stable, it would likely save enough memory to make this work.

**Comment by sgosline** [comment]
I moved it to python, and will be rewriting the entire drug pipeline since it's long overdue. Hold off on doing anything with this right now.

**Comment by jjacobson95** [comment]
Closing issue as the original problem was solved in #101.
